### ISSUE TITLE
docs: outdated config in LiT documentation for MacOS remote mode

### ISSUE THREAD

**Issue by anguschampion** [lightninglabs/docs.lightning.engineering#135]
It looks like the page for [MacOS remote mode configuration](https://github.com/lightninglabs/docs.lightning.engineering/blob/master/lightning-network-tools/lightning-terminal/get-lit/macos-remote-mode.md) for Lightning Terminal is out of date: it suggests copying many more files than required, and suggests outdated config options that now cause errors.

Suggest duplicating the [content in the lightning terminal GitHub](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md), which appears to be accurate. 

I'm happy to take this on, but wanted to flag first.

**Comment by guggero** [comment]
Yeah, this fell out of sync because in the GitHub repo of LiT we only have the generic doc for remote and integrated mode, not split by operating system. At some point we should probably port the docs from this repo to the LiT repo and then auto-sync the files back.

But I guess for now it's easiest to just update the files in this repo. PR is very welcome!
